### PR TITLE
fix: failing test #212

### LINKED ISSUE #212: Fix PublicationPageNavigationTest::testPreviousNextLinks test
There's a recent test failure:

```
1) Drupal\Tests\localgov_publications\Functional\PublicationPageNavigationTest::testPreviousNextLinks
Behat\Mink\Exception\ExpectationException: The string "<a href="/publication-parent-page" rel="prev" title="Go to previous page">" was not found anywhere in the HTML response of the current page.
```

### PR DESCRIPTION
**Pull request by millnut**
## What does this change?

Fixes a failing test #212

### CODE REVIEW

File: tests/src/Functional/PublicationPageNavigationTest.php [hunk 1]
```diff
@@ -91,8 +91,8 @@ public function testPreviousNextLinks() {
 
     $this->drupalLogin($adminUser);
     $this->drupalGet('/node/' . $node_child_one->id());
-    $this->assertSession()->responseContains('<a href="/publication-parent-page" rel="prev" title="Go to previous page">');
```
Comment (rupertj) [inline tests/src/Functional/PublicationPageNavigationTest.php:94]: The test as-is checks the links go to the right place. The updated version only checks that links are present, which feels like a step backwards.  I think the best fix for this would be to use xpath to find the right <a> tags, then check their href attribute is what we expect.

Have you got a link to the failing run so I can get an idea what change broke the test?

**Review by rupertj — DISMISSED** [review]

File: tests/src/Functional/PublicationPageNavigationTest.php (hunk 1 above)
Comment (millnut) [reply tests/src/Functional/PublicationPageNavigationTest.php:94]: Yep it's on the 1.x branch, my guess is a change in localgov_base as latest test runs have gone from 1.6.1 to 1.7.0

Comment (rupertj) [reply tests/src/Functional/PublicationPageNavigationTest.php:94]: You're right. It's this: https://github.com/localgovdrupal/localgov_base/pull/596

**Comment by rupertj** [comment]
@millnut Thanks for highlighting this - I've updated the test so it shouldn't be so fragile when markup changes, and also checks the URL in the links.

Amusingly, the tests still fail because localgov_base is messing with the URL and adding a fragment to it that shouldn't be there. I've raised this issue to cover it: https://github.com/localgovdrupal/localgov_base/issues/640

**Comment by millnut** [comment]
Hey @markconroy could we have a 1.7.2 release of localgov_base so we can re-test this.

**Comment by rupertj** [comment]
@millnut It’s out now :)
